sudo: false
language: python
python:
  - '3.4'
  - '3.5'
sudo: required
env:
  global:
    - secure: MKsfJ8DYCRx7I9bX84ww53Nf/0tgdNYDL1zT17itGfxz9C23rJbiiRrpRyKLCibn+c6ognfighxgnhBTis58m5a/8/06fC/rIM4yVBrok/m/8DNnH5p35QoH3V23TC08nWkwCZfh42DzOX0+63ODK0pvrD2bjDM4cs6+uVnCr3SBEwkOiE087SHGOZAkf4KV9hqm1qqJj0WYWgw1hVYWzfWPLI6jr9kLh1hJ2puMAs6/cry9AuhwyEb3ti+Rng6sIb7Rm86JTaVDNRJlN1Y4IWoINmVP1HhwKOuBVszCUCJwqWfupXrMkeJN2TIsZhM9f27WjjONAGDj3C08pO36qH8pOwTVPjs4Z+loFf5HpIjO+yfYzJ98TENrP39ipwWlVv9L7x0qMP3cLnSIn/TVIM/AXC2dTR3SotU76bX9wNGkdrKfAoeSVc0IJgLrLBtXy244lY9KbO9qvu5f4xyRHrMYVsYZkV+FJ1TQtPDrGu05yiu1Tx5zMb6MGh0YlOYh4YTWOdElXOHw6A0Il+pCLFeEeWh435GHNHpNevudtZ/f4gmtYt65gx2VRhGm2jgefRU+h/Mb2SAB77zIdMXDRTZjMawWqL4enkzJRhF3WT75D0zdNjCrdExMe9muCKbnbpdZHoRniS19u3A++FZt2/j/PkhbYQUuaFEVfSTCDWM=
install: pip install tox-travis
script: tox --travis-after
notifications:
  email:
    recipients:
      - service@soocii.me
deploy:
  provider: pypi
  user: SoociiDev
  password:
    secure: ZwFYgNfPJlhA+2JvRuJur99Xr3ABmYTBeDf5BRiau4A19iC74XODt2AHi1SQF8hCs3IiiTKvogpgRriIIiP14xKeHBbFfF04+Si+2unU6RdQaMcOzNNuYlIto28mpdYmB9I9ROhN6ThUPjheD5p3JkohiPKQtMTOUcs/FazoDsF5U8a+Igb4Z6KRtIXOmMj4PfMr0kThTqSSduhvTVOc2Q5ifJoraTeHdTp/gaIvSyfiHa5+ZOEl8lKSuyzzS47aLxR5ygvBFiY2zdczEykDo0oGKGUdoEYjlFxkOl1JdVBdKmkelXFhgkw+d/r9HlzTm8BdBmeX69xlo/tRxbOuctDF9XouES8ZimFe9IiSbpkqua3u+vuJn4+uLI/hhGBWrUW39wNV4rNX8/ss/ARLoR74Tjla0cemeakCgpNCa6w0Id9yej4qsjB454ghVNDodBWzAtDMT7QxAwG0M44yuN7iIRAhncIIEnNtaZiKwCbhZHUAZ0Z7l++utQ4/gfuWd5f1Z6xKeymp2REogQ6soEDaBW5ljPxAhCdKywDNxk5vFM4FNtWMMk0NsGe1LDQTv76SStU+HoAYrSvvF/ggeoC4FRbXXLY4M+yaEBrPUaYhtco5myvNsmX5VzCsAXuMDvxTwIoImFgh9D0M83EQW1C/XoPlzY8mMiqIte+cMSQ=
  on:
    branch: master
    tags: true
    python: 3.5
