sudo: required
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install: pip install tox-travis
script: tox --travis-after
notifications:
  email:
    recipients:
      - service@soocii.me
deploy:
  provider: pypi
  user: SoociiDev
  password:
    secure: V2Al/N2LbZk5CLn+sfb7Q2dqDiW/vHInSYWrYLGHiPg24+WtXI2hXFgAE6kFIqUfvLFbK89pC/N8ZrI+w9v9pThwcO42mibmcHrspGToJj8f+65hTj0urYHuiwrheh6M8VA5osL71Pz3FLkqWUQCqCMq0OS35m08AYF68idxWkdXTUgORZ5dj5q50MtM3f3ngcC/AxeBhNFIxq2CW7Vl+rkVew3yorOQmTBhPy6PDXw1NuXf/YCC1M3Qk7ii8ei4MPlG6mg2D7tVzstGdIA+4Dy/OcSDxTlAjSnyrNas5lSQvPkL2bPu76OfaNs973JzLvn4gydnEgTU3Ss7VPwjkmI2QM9yMlV7dOQP68YkliGmmnNL82XyBlBQeWFf5zK7z53GBKtQxXWwlhFS3v8cPPUmdZOBGoRwaayqHaBmkCixU65eSGxM1SS/Qk/GpjVBu3t7M++jjAIpOf8fhFkfJYYcsNcRFKphkSAeUPu9toIo4/kGdHRDAPr41PfkZe6H3g7ls5pSCxloQ9eBGhqHHCI0V36dG7W2EUv7xQuSFZpC9PBp7Vh8PmdsAXhmCoGY3E1Rzhsn55bmVlcYj01NB4hPc53y3N3JNX8b8D9KM47Gxfk31qM5SAg9HDO+SjnqNd6Uhy9Dwz6GdZ8KZtOQC/wYTfd0jLMGnS9BlVQmZss=
  on:
    branch: master
    tags: true
    python: 3.5
