sudo: false
language: python
python:
  - '3.4'
  - '3.5'
env:
  global:
    - secure: MKsfJ8DYCRx7I9bX84ww53Nf/0tgdNYDL1zT17itGfxz9C23rJbiiRrpRyKLCibn+c6ognfighxgnhBTis58m5a/8/06fC/rIM4yVBrok/m/8DNnH5p35QoH3V23TC08nWkwCZfh42DzOX0+63ODK0pvrD2bjDM4cs6+uVnCr3SBEwkOiE087SHGOZAkf4KV9hqm1qqJj0WYWgw1hVYWzfWPLI6jr9kLh1hJ2puMAs6/cry9AuhwyEb3ti+Rng6sIb7Rm86JTaVDNRJlN1Y4IWoINmVP1HhwKOuBVszCUCJwqWfupXrMkeJN2TIsZhM9f27WjjONAGDj3C08pO36qH8pOwTVPjs4Z+loFf5HpIjO+yfYzJ98TENrP39ipwWlVv9L7x0qMP3cLnSIn/TVIM/AXC2dTR3SotU76bX9wNGkdrKfAoeSVc0IJgLrLBtXy244lY9KbO9qvu5f4xyRHrMYVsYZkV+FJ1TQtPDrGu05yiu1Tx5zMb6MGh0YlOYh4YTWOdElXOHw6A0Il+pCLFeEeWh435GHNHpNevudtZ/f4gmtYt65gx2VRhGm2jgefRU+h/Mb2SAB77zIdMXDRTZjMawWqL4enkzJRhF3WT75D0zdNjCrdExMe9muCKbnbpdZHoRniS19u3A++FZt2/j/PkhbYQUuaFEVfSTCDWM=
install: pip install tox-travis
script: tox --travis-after
notifications:
  email:
    recipients:
      - service@soocii.me
deploy:
  provider: pypi
  user: calvin620707
  password:
    secure: pU03U7FutNlCBdWLev1t6RLZ7QcZuQM+w9a+/RcQhg9keeAmdoR1BK7P4M+67UpQGu7uopfkWohyvzn9CAq47wLh58mnyw8SWlp+zEk7tpkLlM9xCMTLh8Hx30B1/XJzvX5isBZaMzr8odVCbcVqwPbZQsJj39oOV/g8gp7tKb9P/xgoPXPlirK7T2x+Vto5IKgiDchOfsM248Ksivx3v9VwMyurEi3FPNzutyG8EE+FYydmKGn3iRRx0iEx/OuA4IdpiUukdF7Yn7V8scy25u8qkuPTRnZhZv/1Ls9m8pzfqYrXq+gzp8i39RVF+kk3B/CUrSRBm2v+f2zoiX+sbIi/scRhZwkJsQGDwjPotRJWe2hLAKOyP19VBHbHtZGQhYc933rMAoufV1XdIT5+vBTKE8TJI9M2AMG2Y6TuJoMBvQSSEW5VkEnR7J7AYcJ+pDIXNGEXZLX4nw9+DtKCFx12pL5GvSqVPsnAgIT1TyDIw+YNnbnHXbIKkpHE+Pn23hW8jVrWX5kQ8WFXKjx6XWWhJPPvIX+67SrVpWLWFTQMGbcrB/zm2MXqwpUSn13teFmoWCU8eGA+qIe44GYbUp6VhL83nipfREw+v0LPU9SN8JJaxnA/ALutsr6R9AMIqC52hEPeWUTtCItH79VTETBVAx5uV8uTjQFarv5dva0=
  on:
    branch: master
    tags: true
    python: 3.5
